# Generated by Django 5.2.4 on 2025-07-08 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=120)),
                ('date_paid', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('airtel', 'Airtel Money'), ('tnm', 'TNM Mpamba'), ('bank', 'Bank Transfer')], default='cash', max_length=10)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farmers.farmer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
