# Generated by Django 5.2.4 on 2025-07-08 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmer_options_block_created_at_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-timestamp'], 'permissions': [('verify_payment', 'Can verify payments'), ('view_all_payments', 'Can view all payments')], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('plot_fee', 'Plot Fee'), ('fine', 'Fine'), ('contribution', 'Scheme Contribution'), ('other', 'Other')], default='plot_fee', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='farmers.farmer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('airtel', 'Airtel Money'), ('tnm', 'TNM Mpamba'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
