services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn limphasaScheme.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: limphasa-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: limphasa
          property: connectionString
