# Generated by Django 5.2.4 on 2025-07-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('farmers', '0002_alter_farmer_options_block_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_approve_users', 'Can approve new user registrations'), ('can_assign_roles', 'Can assign roles to users')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='farmers.block'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('block_chair', 'Block Chair'), ('president', 'President'), ('admin', 'Admin'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary')], default='farmer', max_length=20),
        ),
    ]
