# Generated by Django 5.2.4 on 2025-07-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_block_and_more'),
        ('farmers', '0003_remove_block_created_at_remove_block_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='farmers.section'),
        ),
    ]
