# Generated by Django 5.2.4 on 2025-07-08 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('offence_type', models.CharField(choices=[('absence', 'Absence'), ('lateness', 'Lateness'), ('violence', 'Violence'), ('theft', 'Theft'), ('other', 'Other')], max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='discipline_attachments/')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.block')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cases', to='farmers.farmer')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.section')),
            ],
        ),
    ]
