# Generated by Django 5.2.4 on 2025-07-08 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinecase',
            options={'ordering': ['-date_reported'], 'permissions': [('can_escalate_case', 'Can escalate case severity'), ('can_resolve_case', 'Can resolve cases')], 'verbose_name': 'Discipline Case', 'verbose_name_plural': 'Discipline Cases'},
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='date_incident',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='offence_description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinecase',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical')], default='moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='offence_type',
            field=models.CharField(choices=[('absence', 'Absence'), ('lateness', 'Lateness'), ('violence', 'Violence'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('non_compliance', 'Non-compliance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('hearing_scheduled', 'Hearing Scheduled'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('appealed', 'Appealed')], default='open', max_length=20),
        ),
    ]
