# Generated by Django 5.2.4 on 2025-07-14 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_alter_disciplinecase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecase',
            name='action_taken',
            field=models.TextField(blank=True, verbose_name='Action Taken'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='date_incident',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Incident'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='offence_description',
            field=models.TextField(verbose_name='Offence Description'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='offence_type',
            field=models.CharField(choices=[('absence', 'Absence'), ('lateness', 'Lateness'), ('violence', 'Violence'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('non_compliance', 'Non-compliance'), ('other', 'Other')], max_length=20, verbose_name='Offence Type'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AlterField(
            model_name='disciplinecase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
    ]
