# Generated by Django 5.2.4 on 2025-07-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='farmers.block')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('number_of_plots', models.IntegerField()),
                ('amount_per_plot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('chairperson', 'Block Chairperson'), ('president', 'President')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmer_photos/')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.block')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.location')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.section')),
            ],
        ),
    ]
