# Generated by Django 5.2.4 on 2025-07-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance_type', models.CharField(choices=[('general_assembly', 'General Assembly'), ('main_canal_cleaning', 'Main Canal Cleaning'), ('block_canal_cleaning', 'Block Canal Cleaning')], max_length=50)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.block')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.section')),
            ],
            options={
                'unique_together': {('farmer', 'date', 'attendance_type')},
            },
        ),
    ]
