# Generated by Django 5.2.4 on 2025-07-08 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('farmers', '0002_alter_farmer_options_block_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_evidence/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['block_chair', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('general_assembly', 'General Assembly'), ('main_canal_cleaning', 'Main Canal Cleaning'), ('block_canal_cleaning', 'Block Canal Cleaning'), ('training', 'Training Session'), ('field_inspection', 'Field Inspection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='farmers.farmer'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused (With Reason)')], max_length=10),
        ),
    ]
