# Generated by Django 5.2.4 on 2025-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_attendance_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of attendance in minutes'),
        ),
    ]
