# Generated by Django 5.2.4 on 2025-07-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_duration_minutes'),
        ('farmers', '0003_remove_block_created_at_remove_block_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.block'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.section'),
        ),
    ]
